import { atom } from "recoil";

export const beanListState = atom({
  key: "beanListState",
  default: [
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
    {
      nickname: "괜찮은 김우창",
      content: "컨텐츠입니다. 컨텐츠가 많습니다.",
      color: 1,
      img: "",
      createdAt: "",
      latitude: 0,
      longitude: 0,
    },
  ] as {
    nickname: string;
    content: string;
    color: number;
    img: string;
    createdAt: string;
    latitude: number;
    longitude: number;
  }[],
});

export const nameState = atom({
  key: "nameState",
  default: "",
});

export const beanColorState = atom({
  key: "beanColorState",
  default: 0,
});

// export const locationState = atom({
//   key: "locationState",
//   default: {
//     loaded: false,
//     coordinates: { lat: 0, lng: 0 },
//     error: { code: 0, message: "not loaded" },
//   },
// });
